In [1]:
#14. Write a NumPy program to find the number of rows and columns in a given matrix. 

In [2]:
import numpy as np

In [6]:
arr = np.arange(10, 22).reshape((3, 4))
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [8]:
print('Original Matrix!!')
print(arr)

Original Matrix!!
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [9]:
print(arr.shape)

(3, 4)
