In [3]:
#16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [4]:
import numpy as np

In [6]:
arr = np.random.random((3,3,3))

In [7]:
print(arr)

[[[0.45361528 0.90373913 0.16010197]
  [0.36781735 0.39329957 0.17613494]
  [0.56215144 0.45082513 0.05713341]]

 [[0.6165536  0.24756365 0.98710021]
  [0.3029288  0.15310485 0.41032849]
  [0.33801611 0.40343402 0.21411772]]

 [[0.89872554 0.37330146 0.38990109]
  [0.38479319 0.94217417 0.01100466]
  [0.02034357 0.30311457 0.35625572]]]
