In [ ]:
#13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.

In [1]:
import numpy as np

In [9]:
arrrr = np.eye(3)
print(arrrr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
